trigger: none

# jobs: 
# - Run unit tests
# - k8s-linux-default-e2e

resources:
  containers:
  - container: dev1
    image: quay.io/deis/go-dev:v1.17.3

jobs:
- job: unit_tests
  timeoutInMinutes: 60
  cancelTimeoutInMinutes: 5
  strategy:
    maxParallel: 0
    # note: `parallel` and `matrix` are mutually exclusive
    # you may specify one or the other; including both is an error
  pool:
    vmImage: ubuntu-16.04

  container: dev1

  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOROOT: '/usr/local/go1.11' # Go installation path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

  steps:
    - script: |
        mkdir -p '$(GOBIN)'
        mkdir -p '$(GOPATH)/pkg'
        mkdir -p '$(modulePath)'
        shopt -s extglob
        mv !(gopath) '$(modulePath)'
        echo '##vso[task.prependpath]$(GOBIN)'
        echo '##vso[task.prependpath]$(GOROOT)/bin'
      displayName: 'Set up the Go workspace'
    - script: make bootstrap
      displayName: Install dependencies
    - script: make test-style
      displayName: Run linting rules
    - script: make validate-dependencies
      displayName: Check if imports, Gopkg.toml, and Gopkg.lock are in sync
    - script: make build-cross
      displayName: Build cross-architectural binaries
    - script: make coverage
      displayName: Run unit tests and calculate coverage