trigger: none

# jobs: 
# - Run unit tests
# - k8s-linux-default-e2e

resources:
  containers:
  - container: dev1
    image: quay.io/deis/go-dev:v1.17.3

jobs:
- job: unit_tests
  timeoutInMinutes: 60
  cancelTimeoutInMinutes: 5
  strategy:
    maxParallel: 0
    # note: `parallel` and `matrix` are mutually exclusive
    # you may specify one or the other; including both is an error
  pool:
    vmImage: ubuntu-16.04

  container: dev1

  steps:
    - script: echo Hello world